### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [ryo-currency/ryo-gui-wallet#16]
Please provide an AppImage for download. Thanks.

References:
* https://github.com/AppImage/appimage.github.io/pull/883

**Comment by mosu-forge** [comment]
Hi @probonopd this is actually our old GUI wallet, our new Electron based GUI we do have an AppImage available already. I'm going to open a PR to AppImage/appimage.github.io with the correct repo and reference your PR there.

**Comment by probonopd** [comment]
Thank you very much @mosu-forge
